---
name: Builder
on:  # yamllint disable-line rule:truthy
  push:
    tags: ['[0-9].[0-9]+*']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Build with packer
        run: |
          sudo bash -x run.sh
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.AppImage
